version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "demo-web-app"
          ContainerPort: <PORT>
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["<SUBNET-A>","<SUBNET-C>"]
            SecurityGroups: ["<SECURITY-GROUP>"]
            AssignPublicIp: "DISABLED"